require_relative '../book'
require_relative '../person'
require_relative '../rental'
require_relative '../student'
require_relative '../teacher'
require_relative '../decorator'
require_relative '../classroom'
